name: 'CI'
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v3
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # ratchet:actions/setup-node@v3
        with:
          node-version: 20

      # build and test action
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check format and lint
        run: yarn run format-check && yarn lint
      - name: Build and package
        run: yarn build

      # update docs
      - uses: npalm/action-docs-action@9fa96f2c32b29363abe935e2c3d4ee27bc84dce1 # ratchet:npalm/action-docs-action@v2.0.0
  
      - name: Update dist in the repository
        if: github.ref != 'refs/heads/main'

        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # ratchet:stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: 'chore(ci): Updating dist and docs'
          file_pattern: 'dist/* README.md'

      - name: Create Pull Request (main branch only)
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'philips-software'
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # ratchet:peter-evans/create-pull-request@v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(ci): Updating dist and docs'
          title: 'chore(ci): Updating dist and docs'
          branch: update-docs
          branch-suffix: random
          base: ${{ github.event.pull_request.base.ref }}
          delete-branch: true


  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        uses: google-github-actions/release-please-action@cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e # ratchet:google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
